// This file is generated by Slice Machine. Update with care!

import AboutPage from './AboutPage';
import PascalCased from './PascalCased';

export {
	AboutPage,
	PascalCased,
};

export const components = {
	about_page: AboutPage,
	pascal_cased: PascalCased,
};
